[tool.poetry]
name = "quote-scraper"
description = "A tool to scrape quotes from web pages"
version = "0.1.0-dev3"
license = "MIT"

authors = []

readme = "README.md"

repository = "https://github.com/wtfo-guru/quote-scraper"

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.scripts]
qscrape = "quote_scraper.cli:main"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.6"
bs4 = "^0.0.1"
loguru = "^0.7.2"
pyyaml = "^6.0"

[tool.poetry.group.test.dependencies]
mypy = "^1.5"

wemake-python-styleguide = "^0.17"
flake8-pytest-style = "^1.6"
nitpick = "^0.34"

safety = "^2.3"

pytest = "^7.4"
pytest-cov = "^4.1"
pytest-randomly = "^3.12"
isort = "^5.12.0"
black = "^23.9.1"
types-requests = "^2.31.0.8"
types-pyyaml = "^6.0.12.12"
wheel = "^0.41.2"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.1"
sphinx-autodoc-typehints = "^1.24"
m2r2 = "^0.3"
tomli = "^2.0"
doc8 = "^1.0"


[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"


[tool.nitpick]
style = [
  "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml",
  "./.nitpick-wtf-style.toml",
]
